trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: aqciconnect@2
  inputs:
    appURL: 'https://training.accelq.io/'
    userName: 'khushi.chada@accelq.com'
    apiKey: 'FF6hmcDNg52HadcjpBYi6b9ZweJXnGTMoSgzsnjIJi4'
    tenantCode: 'accelqtraining'
    ciJobId: '96550'

# Optional: Ant build step
- task: Ant@1
  inputs:
    workingDirectory: ''
    buildFile: 'build.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true



